baseURL = "http://example.org/"
languageCode = "de-CH"
title = "Portfolio (Book building HUGO-websites)"
# googleAnalytics = "UA-xxx..."
#                 ...+ in head.html add {{template "_internal/google_analytics_async.html" . }}
theme="basic"


[params]
mainSections = ["projects"]
author = "hpsof"
description = "Portfolio Demo-Projekt aus Buch"
github_api_url = "https://api.github.com/users"
github_user = "hpsof"

[caches]
  [caches.getjson]
  # -1 : ewig |  0 : nicht "10s" : 10 sec
  maxAge = 0
